language: node_js
sudo: false
node_js:
- '8'
cache: yarn
jobs:
  include:
    - stage: unit test
      script: yarn test
    - stage: development deploy
      if: NOT type = pull_request
      script:
      - yarn run build
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      - bash ./scripts/deploy.sh s3://dev-search-website
      env:
        - GATSBY_DOMAIN=dev-search.gladly.io
    - stage: production deploy
      if: branch = master AND NOT type = pull_request
      script:
      - yarn run build
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      - bash ./scripts/deploy.sh s3://prod-search-website
      env:
        - GATSBY_DOMAIN=search.gladly.io
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "mhxtGXZXVncuhhbAAtG49QhwSrkNHyKSO/1g5hSXfr27EZkUoGZMXiPBTnMtbkBV6oRwctzGcoaPgWycV4rLRiEzu8O1VNSYT2+K5Xc3N9TMnYj3dyAKuyeW3cvA0gWurFgyyLV9BJmafD8PASnKdDjogGp8YXfDR7DPTgnUZBbdr/4pHjTuHh9uo94aMnmVT/7XP/8nKb91ZjqNSEVCaZYBF9rOQ43yHf6yU/OZlLeiCdD5jgLwhXz5iqA3omRzBuGzGx1w8GUBfES8UvkD3ENwf+lLwfBQ4Tncmzx1HTBP98iNQ2sMZmQLWExuCqisoUXaQngQ+hPtlSDeNArZQV2MLgz4AJE25zeM0dGU/6256mS9yEowV1S8KmDHYDMpcZsUa/EENBAXFZFApKaK2cwra/ZdRVcf59LLRkG6PS/Vs8O3wfgdA93wrthp70vk4SUsJyJP4NxZIef4dr5A4436vkCuqCnrRehsTsgPDLWB/awdUrferxDVrCo16xbY7BL1ZEu2iUF88f2RHVXjmDWIcjviyeHW7uhBiXMvFBTKV3QwtiTY+w1DwdJUuZyUl1D1TrtN8vvBhJ1NYV5p/rocSvxRu5YGRxhfG8P4yXJH9e9nfcyntrTE/885KY7xQzc6vqxxH599CFQDmBo2Qzocinn+4LUd/oeIaB1bauM="
  # AWS_SECRET_ACCESS_KEY
  - secure: "lNg0qJsv3ct+xacWaDumlHu53PZ79B8eZ79N8WuP+6tYvwhxkDkMX/BdgYT4XMFIpKoybve7vKuve5F5nNIZiye2fysu/12qKymi6tZ9tMmd8qNo5QkCTYgGJ6OwGd2pYBWQVZeWfm1mo2cUWi/YcazDbvHMUwPXy1o6tj3AiDrzTOWZpxKOcSS46+d1r0JGZ7u5NjYVuMXXMhRtbpXhjUwS9gF7A2wCscV6ooi04c6b+O27FzkNvCKWg3ilwsLf/jO1dAeKhoFyr0mU/ETtrtHpZBdSXHZmDMtsgrJ0g11z4bknLIU0d9/V9FnGIvUpVSB2AND+0lCCs1Udncb5GyyYeAPu0XorQMAddjUsdGMWswNzMj3ZTV9HQ5ZXpcSHKgA+g1ye0A6YqPkhKrt7OvJqJgql9j8eDBzKxNV/kaolw8Hel7MjgfdtS2kLu0WQqKr1KGl0hgpC52Clz/XNmygWxVUcto3jGM/I2ZtuNz8iMsqyFnrSAJkmvqaKAdBqsCoQvxoK082Lh4anVF/1/NLb1fATzYW7R/zuqHbJbJ/XVoLzMQ0LLd36f8xJqWANc3h1XUorcP77qC7KkiCUqsXaq5lPks3Q2YMgeURRhZ4333zCUW6qXiqJiWvB1EIeRIdmTipo1LHt2jm6Ntjf/CteMOB47vEjy8wRjOnEE7Y=" 
