language: node_js
sudo: false
node_js:
- '8'
cache: yarn
jobs:
  include:
    - stage: unit test
      script: yarn test
    - stage: development deploy
      if: NOT type = pull_request
      script:
      - yarn run build
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      - bash ./scripts/deploy.sh s3://dev-search-website
      env:
        - GATSBY_DOMAIN=dev-search.gladly.io
    - stage: production deploy
      if: branch = master AND NOT type = pull_request
      script:
      - yarn run build
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      - bash ./scripts/deploy.sh s3://prod-search-website
      env:
        - GATSBY_DOMAIN=search.gladly.io
env:
  global:
  # AWS_ACCESS_KEY
  - secure: "wdSeXgBWv2g0N6vJkHzAWgHhzFUgZJyzjJo61gCAtORn6+jVYasI/7JzKJsE308tkbpvUBmD0uDjoPflvFVbkUPyAzh0LJV0jkXg4W4bSO2XpYwjKsiR4Q27vCMaunFLkqxFOvMmr+ctKSaZE1UUkpWeGSDs7dYo7PFWNJ9MdKHFC3YvpKe29YfxyXIIg8Aex3x/41+nfpT1ZzpOwYHpGqfx6mNEQaz/raEnzRt823a6VQrVDGzA0ZINiBrf2rXQNcHB5gWPu8YK5DN5k90SfzsJArTxEgwL81yMgNddmFRmVsG51eY94dyp6jyf5VbqruHqeMtv4XtVoJMkMtSmWCkRDa2ODWwVemybEy2pMCRfqFBJ7gO7aazQdYcTwdr6vt5hQnHoJWHnat3/KYVzLsPsn13/nW72zSMUpLr+gQ8hHWyef6YuqLOFqJp2hDk9b4S3nd1VlL7TkA/uVRrlei/l42W51pw0Giu9mrNfPuCIfe10zRt5lQXc2oCR48NYgqfJdqUYMELWA+Na+7aOiKH3TZc96zOG9bgG938CqLEsG0p0GyuLpTonQvpfGtAUFdfNBNzoKECht7KggeMdoXt1FagCsM9tYJWQanENzD0EprdtBNQnB5sjBuUNcqMT1H+XwgmS7NOj12CbsR7lAVpcZ2TpwBcDtODBWPxMBIw="
  # AWS_SECRET_ACCESS_KEY
  - secure: "lNg0qJsv3ct+xacWaDumlHu53PZ79B8eZ79N8WuP+6tYvwhxkDkMX/BdgYT4XMFIpKoybve7vKuve5F5nNIZiye2fysu/12qKymi6tZ9tMmd8qNo5QkCTYgGJ6OwGd2pYBWQVZeWfm1mo2cUWi/YcazDbvHMUwPXy1o6tj3AiDrzTOWZpxKOcSS46+d1r0JGZ7u5NjYVuMXXMhRtbpXhjUwS9gF7A2wCscV6ooi04c6b+O27FzkNvCKWg3ilwsLf/jO1dAeKhoFyr0mU/ETtrtHpZBdSXHZmDMtsgrJ0g11z4bknLIU0d9/V9FnGIvUpVSB2AND+0lCCs1Udncb5GyyYeAPu0XorQMAddjUsdGMWswNzMj3ZTV9HQ5ZXpcSHKgA+g1ye0A6YqPkhKrt7OvJqJgql9j8eDBzKxNV/kaolw8Hel7MjgfdtS2kLu0WQqKr1KGl0hgpC52Clz/XNmygWxVUcto3jGM/I2ZtuNz8iMsqyFnrSAJkmvqaKAdBqsCoQvxoK082Lh4anVF/1/NLb1fATzYW7R/zuqHbJbJ/XVoLzMQ0LLd36f8xJqWANc3h1XUorcP77qC7KkiCUqsXaq5lPks3Q2YMgeURRhZ4333zCUW6qXiqJiWvB1EIeRIdmTipo1LHt2jm6Ntjf/CteMOB47vEjy8wRjOnEE7Y=" 
