name: Run tests

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test # generates coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
      - name: Build
        run: yarn run build # ensure build does not error
